### ISSUE TITLE
Deployment of replication mariadb server 

### ISSUE THREAD

**Issue by rashiga** [geerlingguy/mariadb-operator#13]
I am trying to deploy a Mariadb server with 1 master and 2 replicas. The database.yml is as follows:
```
apiVersion: mariadb.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: example-mariadb
  namespace: example-mariadb
spec:
  masters: 1
  replicas: 2
  mariadb_password: CHANGEME
  mariadb_image: mariadb:10.5
  mariadb_pvc_storage_request: 1Gi
```
The statefulset is getting deployed with just one pod. I think [`replicas: 1`](/geerlingguy/mariadb-operator/blob/master/roles/mariadb/templates/mariadb_statefulset.yaml.j2#L14) is hardcorded which is the reason this is happening.
