### ISSUE TITLE
Create thorough README with usage and maintenance information

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/mariadb-operator#6]
I need a lot more info in the README to keep myself up to speed, and to onramp new users more easily. It's pretty sparse right now :)

One especially important thing is to show someone how, after they deploy the operator, they can test it out quickly:

    kubectl -n example-mariadb run -it --rm mysql-client --image=arey/mysql-client --restart=Never -- -h example-mariadb.example-mariadb.svc.cluster.local -u db_user -pTODO -D db
    MariaDB [db]>

**Comment by geerlingguy** [comment]
After #7, new command to connect is:

```
kubectl -n example-mariadb run -it --rm mysql-client --image=arey/mysql-client --restart=Never -- -h example-mariadb-0.example-mariadb.example-mariadb.svc.cluster.local -u db_user -pCHANGEME -D db
```

**Comment by geerlingguy** [comment]
Another thing I'd like to do is show how easy it is to create a service to expose a particular pod (e.g. index `-0` for the default master) to the external world: https://itnext.io/exposing-statefulsets-in-kubernetes-698730fb92a1

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mariadb-master
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/example-mariadb: example-mariadb-0
  ports:
  - protocol: TCP
    port: 3360
    targetPort: 3360
```
